all:
	pdflatex -shell-escape 01-introduccion.tex

clean:
	rm -rf _minted-01-introduccion
	rm 01-introduccion.aux 01-introduccion.log 01-introduccion.nav 01-introduccion.out 01-introduccion.snm 01-introduccion.toc 01-introduccion.vrb
