all:
	pdflatex -shell-escape presentacion.tex

clean:
	rm -rf _minted-presentacion
	rm presentacion.aux presentacion.log presentacion.nav presentacion.out presentacion.snm presentacion.toc presentacion.vrb
